title: Andre Costa Dev
author: andrer54
email: andrer54@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Desenvolvedor backend Jr. 
  Em transição de carreira
  Buscando a primeira oportunidade como Desenvolvedor.

# social links
twitter_username: ANDRESHRED # DO NOT include the @ character, or else the build will fail!
github_username:  andrer54 # DO NOT include the @ character, or else the build will fail!
linkedin_username: andrecosta110 #DO IT YOURSELF

show_excerpts: true # set to false to remove excerpts on the homepage

#theme: minima
remote_theme : "manid2/lone-wolf-theme"
